### PR TITLE
Adding options for allDay and noEvents label

### PR DESCRIPTION
**Pull request by shinrox**

### CODE REVIEW

**Comment by twinssbc** [comment]
@shinrox Thanks for submitting the PR. I merged into my repository and did some small change. Also I decide not to enable ng-bind-html on the event title, as I think the display should be controlled by the view, instead of the underlying data model.

**Comment by shinrox** [comment]
I saw the changes, no problems = ), I understand what you said about the html, but how can I change if I don't control the view? 

To include icons for example, should be an option?

screen shot 2016-04-18 at 9 24 19 am

**Comment by twinssbc** [comment]
@shinrox I get your requirement. I think I will switch to use ng-bind-template to provide the customization.

**Comment by twinssbc** [comment]
@shinrox Sorry, click too fast that I deleted your reply.
I get your point, I will think about it.

**Comment by shinrox** [comment]
haha, Ok, Thanks = )

**Pull request closed without merging**
