### PR TITLE
Add className attribute in eventSource for Week & Day views

### PR DESCRIPTION
**Pull request by mittalrahul**
The `className` attribute in the `eventSource` Object can be used to pass a CSS Class to the event Element.

The CSS Class passed will apply only in the Week & Day views.

### CODE REVIEW

**Comment by twinssbc** [comment]
@mittalrahul Thanks for the pull request. I understand the idea you want to customize the display event. But I think passing className in the eventSource is not the best solution.
Because eventSource is a dataObject, it should not contain any information related to the view, and also I guess the className will likely always the same, so no need to pass className in every event.
If you want to customize the display event, I think you can directly override the style in calendar-event css class?
If you want to display different content for different type of event, I think the better solution is to make the calendar control accepts a customized template.

**Comment by mittalrahul** [comment]
@twinssbc I agree with your thoughts to override the `calendar-event.css` but what if we want to display 3 types of events in the calendar and each type of event has different background color.

And even if we use the customized template, we still have to pass the className to the separate type of events.

**Comment by twinssbc** [comment]
If event type is already passed, passing className is kind of duplication.
className can be generated based on the event type, and it should be done by the view, instead of the data layer. Otherwise underlying data format is coupled with the view.

**Comment by twinssbc** [comment]
@mittalrahul I have added view customisation support in version 0.3.0

**Comment by mittalrahul** [comment]
@twinssbc Thanks for the Template Customization support.

**Pull request closed without merging**
